#!/usr/bin/perl -w

use strict;

my $filename = shift;
my $perl;

open (PLFILE, "<$filename") || die "can't open $filename: $!\n";
while (defined ($perl = <PLFILE>))
  {
	 chomp $perl;
	 $perl =~ s%\\%\\\\%g;
	 $perl =~ s%\"%\\\"%g;
	 print "\"$perl\\n\"\n";
  }
close PLFILE;
